# Generated by Django 2.2.7 on 2019-11-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1_1', models.CharField(default='3', max_length=50)),
                ('answer1_2', models.CharField(default='22', max_length=50)),
                ('answer1_3', models.CharField(default='open', max_length=50)),
                ('answer2_1', models.CharField(default='rouge', max_length=50)),
                ('answer2_2', models.CharField(default='vermeil', max_length=50)),
                ('answer2_3', models.CharField(default='herodote', max_length=50)),
                ('answer3_1', models.CharField(default='secret', max_length=50)),
                ('answer3_2', models.CharField(default='virgule', max_length=50)),
                ('answer3_3', models.CharField(default='rdvnatio', max_length=50)),
            ],
            options={
                'verbose_name': 'Reponse',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('score', models.IntegerField()),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('t_answer1_1', models.IntegerField()),
                ('tentative1_1', models.IntegerField(default=0)),
                ('t_answer1_2', models.IntegerField()),
                ('tentative1_2', models.IntegerField(default=0)),
                ('t_answer1_3', models.IntegerField()),
                ('tentative1_3', models.IntegerField(default=0)),
                ('t_answer2_1', models.IntegerField()),
                ('tentative2_1', models.IntegerField(default=0)),
                ('t_answer2_2', models.IntegerField()),
                ('tentative2_2', models.IntegerField(default=0)),
                ('t_answer2_3', models.IntegerField()),
                ('tentative2_3', models.IntegerField(default=0)),
                ('t_answer3_1', models.IntegerField()),
                ('tentative3_1', models.IntegerField(default=0)),
                ('t_answer3_2', models.IntegerField()),
                ('tentative3_2', models.IntegerField(default=0)),
                ('t_answer3_3', models.IntegerField()),
                ('tentative3_3', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Resultat',
            },
        ),
    ]
